# Generated by Django 4.0.3 on 2022-03-10 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0002_alter_uploaddoc_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=50)),
                ('folder_created_date', models.DateTimeField(auto_now_add=True)),
                ('creater_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creater_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
