# Generated by Django 4.0.3 on 2022-03-10 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_folder_upload_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='upload_doc',
        ),
        migrations.AddField(
            model_name='uploaddoc',
            name='folder_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='folder', to='upload.folder'),
            preserve_default=False,
        ),
    ]
