# Generated by Django 4.0.3 on 2022-03-10 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_remove_folder_upload_doc_uploaddoc_folder_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploaddoc',
            name='folder_name',
        ),
        migrations.AddField(
            model_name='uploaddoc',
            name='folder_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_file', to='upload.folder'),
        ),
    ]
