# Generated by Django 4.0.3 on 2022-03-10 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0006_remove_uploaddoc_folder_name_uploaddoc_folder_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploaddoc',
            name='user',
        ),
        migrations.AddField(
            model_name='folder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
