# Generated by Django 4.0.3 on 2022-03-22 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0008_remove_folder_creater_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='creater_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creater_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
